main: me.davidjdm.QuickTree.Console
name: QuickTree
version: 1.3.1
author: DavidJDM
description: Breaks the whole tree if bottom block is broken
permission-message: ยง4You do not have the permission to this command!
commands:
  quicktree:
    description: Main command for QuickTree plugin
    aliases: [qt]
Permissions:
  quicktree.*:
    description: Allows player to use all of QuickTree permissions
    children:
      quicktree: true
      quicktree.use: true
      quicktree.help: true
      quicktree.toggle: true
      quicktree.tool: true
      quicktree.tool.toggle: true
      quicktree.tool.bind: true
  quicktree:
    description: Access to /qt
  quicktree.use:
    description: Access to use plugin
  quicktree.help:
    description: Access to /qt help
  quicktree.toggle:
    description: Access to /qt toggle
  quicktree.tool:
    description: Access to /qt tool
  quicktree.tool.*:
    children:
      quicktree.tool.toggle: true
      quicktree.tool.bind: true
      description: Access to all /qt tool <command> commands
    description: Access to /qt tool
  quicktree.tool.toggle:
    description: Access to /qt tool toggle
  quicktree.tool.bind:
    description: Access to /qt tool bind